### PR TITLE
Update cf_byte_order.h to silence a gcc strict aliasing warning

### PR DESCRIPTION
**Pull request by bsergean**
See https://github.com/aerospike/aerospike-client-c/issues/102

### CODE REVIEW

**Comment by BrianNichols** [comment]
It's currently expected that header files (in addition to *.c files) should be compiled with "-fno-strict-aliasing".

**Comment by bsergean** [comment]
Ok. If you guys are unlikely to merge this I will close this.

It's just a note that random C/C++ app might set -fstrict-aliasing as a global scale settings, and get a wall of warning because of this.

We can re-open if you get more reports / asks about this maybe ?

**Comment by BrianNichols** [comment]
The proposed solution suppresses warnings (ignore "-Wstrict-aliasing"), but the compiler probably still follows strict aliasing assumptions and therefore optimizations. "-fno-strict-aliasing" tells the compiler to not perform optimizations related to strict aliasing assumptions.  Linux is also compiled with "-fno-strict-aliasing" (See https://www.mail-archive.com/linux-btrfs@vger.kernel.org/msg01647.html).

Yes, we might revisit this if it becomes a significant problem and there was a more comprehensive solution.

**Comment by bsergean** [comment]
Alright no worries. We've put those pragma in our code base so we aren't being bugged anymore, but it would be ideal to solve this for everyone.

**Pull request closed without merging**
