### PR TITLE
Fix compilation on FreeeBSD alloca.h not found

### PR DESCRIPTION
**Pull request by Martinfx**

### CODE REVIEW

**Comment by Martinfx** [comment]
I am very sorry this commit is bad, i will send new commit.

**Comment by Martinfx** [comment]
Problem is on FreeBSD with header alloca.h  doesnt exists, but it contains in header stdlib.h.

**Comment by BrianNichols** [comment]
We will replace alloca.h with stdlib.h in the next client release.

**Comment by Martinfx** [comment]
Ok can i close this pull request or you will make merge ?

**Comment by BrianNichols** [comment]
First, I will merge into our private repository.  Upon next C client release, the change will appear in the public repo.

**Comment by Martinfx** [comment]
Thanks you for answer Brain.
M.

**Comment by Martinfx** [comment]
In new release still same problem with alloca.h

**Comment by BrianNichols** [comment]
Did you update your submodules in the C client?

**Comment by Martinfx** [comment]
I am sorry Brian my problem. Thank you M.

**Pull request closed without merging**
